name: sal
favicon: null
layout_spectrum: 0.99904
typography_spectrum: 0.8983390636276454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050608'
    - '#e4aa9c'
    - '#e5e3ea'
    - '#5f526b'
    - '#b65241'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.9777984861284494
purpose: []
